#!/usr/bin/env python3
"""Validate counterexamples/*/case.json and generate the derived files.

Generated (checked in; never edit by hand):
  tex/generated/ledger.tex     admitted-archive ledger longtable
  tex/generated/dossiers.tex   dossier section: subsection titles, credit
                               lines, and \\input of each dossier body
  registry.json                flattened machine-readable registry (all cases,
                               including withheld ones)
  README.md                    case table between the BEGIN/END CASE TABLE markers

Usage:
  python tools/build.py                validate and regenerate
  python tools/build.py --check        fail (exit 1) if generated files are stale
  python tools/build.py --allow-todo   tolerate TODO found_by values (migration only)

Stdlib only. All validation errors are collected and reported together.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CASES_DIR = ROOT / "counterexamples"
GENERATED_DIR = ROOT / "tex" / "generated"
REFERENCES_BIB = ROOT / "tex" / "references.bib"
README = ROOT / "README.md"
REGISTRY = ROOT / "registry.json"

CLASSES = {
    "published theorem",
    "published conjecture",
    "external conjecture",
    "external formal problem",
    "user formal problem",
}
CERTIFICATE_LEVELS = {"exact", "computer-assisted"}
DATE_RE = re.compile(r"^\d{4}-\d{2}(-\d{2})?$")
GENERATED_HEADER = "% GENERATED by tools/build.py -- do not edit\n"
TABLE_BEGIN = "<!-- BEGIN CASE TABLE -->"
TABLE_END = "<!-- END CASE TABLE -->"


def fail(errors):
    for e in errors:
        print("error:", e, file=sys.stderr)
    sys.exit(1)


def balanced_braces(s):
    depth = 0
    for ch in s:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                return False
    return depth == 0


def load_cases(errors):
    cases = []
    for d in sorted(CASES_DIR.iterdir()):
        if not d.is_dir() or d.name.startswith("_"):
            continue
        f = d / "case.json"
        if not f.exists():
            errors.append(f"case {d.name}: missing case.json")
            continue
        try:
            case = json.loads(f.read_text())
        except json.JSONDecodeError as e:
            errors.append(f"case {d.name}: invalid JSON in case.json ({e})")
            continue
        case["_dir"] = d
        cases.append(case)
    return cases


def is_todo(v):
    return not isinstance(v, str) or not v.strip() or v.strip().upper().startswith("TODO")


def validate(cases, allow_todo, errors):
    bib_keys = set(re.findall(r"@\w+\{([^,\s]+)\s*,", REFERENCES_BIB.read_text()))
    seen_orders = {}
    seen_result_ids = {}
    seen_labels = {}

    for c in cases:
        cid = c.get("id", c["_dir"].name)

        def err(msg):
            errors.append(f"case {cid}: {msg}")

        if c.get("id") != c["_dir"].name:
            err(f'id "{c.get("id")}" does not equal directory name "{c["_dir"].name}"')
        for field in ("title", "status", "results", "credits", "verify", "artifacts"):
            if field not in c:
                err(f"missing required field {field!r}")
        status = c.get("status")
        if status not in ("refuted", "withheld"):
            err(f'status must be "refuted" or "withheld", got {status!r}')

        if status == "refuted":
            order = c.get("order")
            if not isinstance(order, int) or order < 1:
                err("refuted case needs a positive integer 'order'")
            elif order in seen_orders:
                err(f"order {order} already used by case {seen_orders[order]}")
            else:
                seen_orders[order] = cid
            dossier = c.get("dossier")
            if not dossier:
                err("refuted case needs a 'dossier' file")
            elif not (c["_dir"] / dossier).exists():
                err(f"dossier file {dossier} does not exist")
        elif status == "withheld":
            if is_todo(c.get("withheld_reason")):
                err("withheld case needs a non-empty 'withheld_reason'")
            if c.get("order") is not None:
                err("withheld case must not have an 'order'")
            paper = c.get("paper")
            if paper and not (c["_dir"] / paper).exists():
                err(f"paper file {paper} does not exist")

        for key in c.get("bib_keys", []):
            if key not in bib_keys:
                err(f"bib key {key!r} not found in tex/references.bib")

        results = c.get("results") or []
        if not results:
            err("needs at least one entry in 'results'")
        dossier_text = ""
        if status == "refuted" and c.get("dossier") and (c["_dir"] / c["dossier"]).exists():
            dossier_text = (c["_dir"] / c["dossier"]).read_text()
        for r in results:
            rid = r.get("id")
            if not rid:
                err("result missing 'id'")
                continue
            if rid in seen_result_ids:
                err(f"result id {rid!r} already used by case {seen_result_ids[rid]}")
            seen_result_ids[rid] = cid
            for field in ("statement_tex", "class", "certificate_level", "certificate_tex"):
                if is_todo(r.get(field)):
                    err(f"result {rid}: missing or TODO field {field!r}")
            if r.get("class") not in CLASSES:
                err(f"result {rid}: class {r.get('class')!r} not one of {sorted(CLASSES)}")
            if r.get("certificate_level") not in CERTIFICATE_LEVELS:
                err(
                    f"result {rid}: certificate_level {r.get('certificate_level')!r} "
                    f"not one of {sorted(CERTIFICATE_LEVELS)}"
                )
            for field in ("statement_tex", "certificate_tex"):
                v = r.get(field)
                if isinstance(v, str) and not balanced_braces(v):
                    err(f"result {rid}: unbalanced braces in {field}")
            label = r.get("theorem_label")
            if status == "refuted":
                if not label:
                    err(f"result {rid}: refuted result needs a theorem_label")
                else:
                    if label in seen_labels:
                        err(f"result {rid}: theorem_label {label!r} already used by {seen_labels[label]}")
                    seen_labels[label] = cid
                    if f"\\label{{{label}}}" not in dossier_text:
                        err(f"result {rid}: \\label{{{label}}} not found in {c.get('dossier')}")

        credits = c.get("credits") or {}
        for role in ("posed_by", "formalized_by", "audited_by", "contributed_by"):
            if is_todo(credits.get(role)):
                err(f"credits.{role} is missing or TODO")
        found = credits.get("found_by") or {}
        model, date = found.get("model"), found.get("date")
        if is_todo(model) or is_todo(date):
            if allow_todo:
                print(f"warning: case {cid}: credits.found_by has TODO values", file=sys.stderr)
            else:
                err("credits.found_by needs a real model and date (run with --allow-todo during migration)")
        elif not DATE_RE.match(date):
            err(f"credits.found_by.date {date!r} must match YYYY-MM or YYYY-MM-DD")

        verify = c.get("verify") or {}
        py = verify.get("python")
        if not py:
            err("verify.python is required")
        elif not (c["_dir"] / py).exists():
            err(f"verify.python file {py} does not exist")
        for s in verify.get("sage", []):
            if not (c["_dir"] / s).exists():
                err(f"verify.sage file {s} does not exist")

        for a in c.get("artifacts", []):
            if is_todo(a.get("description")):
                err(f"artifact {a.get('file')}: missing or TODO description")


def refuted_in_order(cases):
    return sorted((c for c in cases if c["status"] == "refuted"), key=lambda c: c["order"])


def withheld_sorted(cases):
    return sorted((c for c in cases if c["status"] == "withheld"), key=lambda c: c["id"])


STATUS_MACROS = {"refuted": r"\statusfalse"}


def gen_ledger(cases):
    lines = [
        GENERATED_HEADER + r"\section{Audited archive ledger}",
        "",
        r"\begin{longtable}{@{}p{0.06\textwidth}p{0.33\textwidth}p{0.15\textwidth}p{0.34\textwidth}@{}}",
        r"\caption{Admitted session-derived disproofs.}\label{tab:ledger}\\",
        r"\toprule",
        r"No. & Formal statement & Status & Certificate \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"No. & Formal statement & Status & Certificate \\",
        r"\midrule",
        r"\endhead",
    ]
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            lines.append(
                f"{n} & {r['statement_tex']} & {STATUS_MACROS[c['status']]} & {r['certificate_tex']}\\\\"
            )
    lines += [r"\bottomrule", r"\end{longtable}", ""]
    return "\n".join(lines)


def credit_line(c):
    cr = c["credits"]
    found = cr["found_by"]
    parts = [
        f"Posed by {cr['posed_by']}",
        f"counterexample found by {found['model']} ({found['date']})",
        f"formalized by {cr['formalized_by']}",
        f"audited by {cr['audited_by']}",
    ]
    if cr.get("contributed_by") and cr["contributed_by"] != cr["formalized_by"]:
        parts.append(f"contributed by {cr['contributed_by']}")
    return "; ".join(parts) + "."


def gen_dossiers(cases):
    blocks = [GENERATED_HEADER + r"\section{Counterexample dossiers}"]
    for c in refuted_in_order(cases):
        title = c.get("title_tex") or c["title"]
        blocks.append(
            "\n".join(
                [
                    f"\\subsection{{{title}}}",
                    f"\\dossiercredits{{{credit_line(c)}}}",
                    f"\\input{{../counterexamples/{c['id']}/{c['dossier']}}}",
                ]
            )
        )
    return "\n\n".join(blocks) + "\n"


def gen_registry(cases):
    entries = []
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            entries.append((c, r, n))
    for c in withheld_sorted(cases):
        for r in c["results"]:
            entries.append((c, r, None))
    out = []
    for c, r, ledger_no in entries:
        out.append(
            {
                "result_id": r["id"],
                "case": c["id"],
                "title": c["title"],
                "status": c["status"],
                "ledger_no": ledger_no,
                "withheld_reason": c.get("withheld_reason"),
                "class": r["class"],
                "certificate_level": r["certificate_level"],
                "certificate_tex": r["certificate_tex"],
                "theorem_label": r.get("theorem_label"),
                "credits": {k: v for k, v in c["credits"].items()},
                "verify": c["verify"],
            }
        )
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


def gen_readme_table(cases):
    lines = [
        "| No. | Case | Status | Class | Certificate | Found by |",
        "|---|---|---|---|---|---|",
    ]
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            found = c["credits"]["found_by"]
            lines.append(
                f"| {n} | [{r['id']}](counterexamples/{c['id']}/) | refuted "
                f"| {r['class']} | {r['certificate_level']} | {found['model']} ({found['date']}) |"
            )
    for c in withheld_sorted(cases):
        for r in c["results"]:
            found = c["credits"]["found_by"]
            lines.append(
                f"| — | [{r['id']}](counterexamples/{c['id']}/) | withheld "
                f"| {r['class']} | {r['certificate_level']} | {found['model']} ({found['date']}) |"
            )
    return "\n".join(lines)


def splice_readme(table):
    text = README.read_text()
    if TABLE_BEGIN not in text or TABLE_END not in text:
        fail([f"README.md: markers {TABLE_BEGIN} / {TABLE_END} not found; refusing to guess"])
    head, rest = text.split(TABLE_BEGIN, 1)
    _, tail = rest.split(TABLE_END, 1)
    return head + TABLE_BEGIN + "\n" + table + "\n" + TABLE_END + tail


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--allow-todo", action="store_true", help="tolerate TODO found_by values")
    args = parser.parse_args()

    errors = []
    cases = load_cases(errors)
    validate(cases, args.allow_todo, errors)
    if errors:
        fail(errors)

    outputs = {
        GENERATED_DIR / "ledger.tex": gen_ledger(cases),
        GENERATED_DIR / "dossiers.tex": gen_dossiers(cases),
        REGISTRY: gen_registry(cases),
        README: splice_readme(gen_readme_table(cases)),
    }

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in outputs.items()
            if not path.exists() or path.read_text() != content
        ]
        if stale:
            fail([f"stale generated file: {p} (run python tools/build.py)" for p in stale])
        print("generated files up to date")
        return

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content)
        print("wrote", path.relative_to(ROOT))


if __name__ == "__main__":
    main()
