#!/usr/bin/env python3
"""Validate counterexamples/*/case.json and generate the derived files.

Generated (checked in; never edit by hand):
  tex/generated/ledger.tex     admitted-archive ledger longtable
  tex/generated/dossiers.tex   dossier section: subsection titles, credit
                               lines, and \\input of each dossier body
  registry.json                flattened machine-readable registry (all cases,
                               including withheld ones)
  README.md                    case table between the BEGIN/END CASE TABLE markers

Usage:
  python tools/build.py                validate and regenerate
  python tools/build.py --check        fail (exit 1) if generated files are stale
  python tools/build.py --allow-todo   tolerate TODO found_by values (migration only)

Stdlib only. All validation errors are collected and reported together.
"""
from __future__ import annotations

import argparse
import json
import re
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CASES_DIR = ROOT / "counterexamples"
GENERATED_DIR = ROOT / "tex" / "generated"
REFERENCES_BIB = ROOT / "tex" / "references.bib"
README = ROOT / "README.md"
REGISTRY = ROOT / "registry.json"

CLASSES = {
    "published theorem",
    "published conjecture",
    "external conjecture",
    "external formal problem",
    "user formal problem",
}
CERTIFICATE_LEVELS = {"exact", "computer-assisted"}
# How faithfully result.provenance.statement_tex reproduces the source.  Only
# "verbatim" is rendered as a quotation of the original; "paraphrase" is labelled
# as such in the paper so a restatement is never passed off as the original.
FIDELITIES = {"verbatim", "paraphrase"}
# Cases sharing a group key are emitted as subsections of one common section
# instead of one section each; their 'order' values must be consecutive.
GROUPS = {"aim": "Borcea--Br\\\"and\\'en AIM problems"}
DATE_RE = re.compile(r"^\d{4}-\d{2}(-\d{2})?$")
# Immutable per-result identity, and the primary key of registry.json.  The
# alphabet is Crockford base32 -- no I, L, O or U -- so a uid survives being
# read aloud or retyped, and cannot spell a word by accident.  It is random
# rather than derived from the case, because a content-derived key would change
# every time a statement was corrected, which is the opposite of identity.
#
# A uid is never cited: humans cite the result id.  This exists so that renaming
# a result later does not break a database row pointing at it.
CREDIT_ROLES = {"posed_by", "found_by", "formalized_by", "audited_by", "contributed_by"}
UID_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
UID_LEN = 8
UID_RE = re.compile(rf"^[{UID_ALPHABET}]{{{UID_LEN}}}$")


def mint_uid():
    return "".join(secrets.choice(UID_ALPHABET) for _ in range(UID_LEN))


def committed_uid_bindings():
    """Map result_id -> uid as of the registry currently on disk.

    registry.json is generated, so this is the binding that last survived
    review; comparing new metadata against it is what makes a uid immutable in
    practice rather than only by convention.
    """
    if not REGISTRY.exists():
        return {}
    try:
        rows = json.loads(REGISTRY.read_text())
    except json.JSONDecodeError:
        return {}
    return {r["result_id"]: r["uid"] for r in rows if isinstance(r, dict) and r.get("uid")}
GENERATED_HEADER = "% GENERATED by tools/build.py -- do not edit\n"
TABLE_BEGIN = "<!-- BEGIN CASE TABLE -->"
TABLE_END = "<!-- END CASE TABLE -->"


def fail(errors):
    for e in errors:
        print("error:", e, file=sys.stderr)
    sys.exit(1)


def balanced_braces(s):
    depth = 0
    for ch in s:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                return False
    return depth == 0


def read_sidecar(case_dir, name, errors, where):
    """Read a prose sidecar, or record an error naming the file that is missing.

    Whole-line LaTeX comments are dropped: the templates carry their
    instructions as comments, and those must neither reach the paper nor hide an
    unfilled TODO from the build.  Surrounding blank lines then go too, so the
    text matches what an equivalent JSON string literal would have held.
    """
    path = case_dir / name
    if not path.exists():
        errors.append(f"{where}: sidecar file {name!r} does not exist")
        return ""
    lines = path.read_text().splitlines()
    return "\n".join(l for l in lines if not l.lstrip().startswith("%")).strip("\n")


def load_sidecars(case, d, errors):
    """Resolve prose files into the fields the rest of the build already expects.

    LaTeX lives in .tex files, not in JSON string literals: a paragraph of
    mathematics inside JSON has to double every backslash and collapse to a
    single line, which is miserable to write and worse to review.  case.json
    names the file; this function substitutes its contents, so everything
    downstream sees exactly the structure it saw before.
    """
    cid = case.get("id", d.name)
    if "context_tex" in case:
        errors.append(
            f"case {cid}: 'context_tex' is no longer read from case.json; "
            "move the prose into a .tex file and name it in 'context'"
        )
    name = case.pop("context", None)
    if name:
        # Underscore-prefixed, so it stays out of the generated registry; kept
        # only so that an error can name the file the author must actually edit.
        case["_context_file"] = name
        case["context_tex"] = read_sidecar(d, name, errors, f"case {cid}")

    seen = {}
    for r in case.get("results") or []:
        rid = r.get("id", "?")
        prov = r.get("provenance")
        if not isinstance(prov, dict):
            continue
        if "statement_tex" in prov:
            errors.append(
                f"case {cid}: result {rid}: provenance 'statement_tex' is no longer read "
                "from case.json; move the quoted statement into a .tex file and name it "
                "in provenance 'statement'"
            )
        name = prov.pop("statement", None)
        if not name:
            continue
        # Two results quoting the same file would silently attribute one
        # source's words to the other statement.
        if name in seen:
            errors.append(
                f"case {cid}: result {rid}: statement file {name!r} is already used by "
                f"result {seen[name]}"
            )
        seen[name] = rid
        r["_statement_file"] = name
        prov["statement_tex"] = read_sidecar(d, name, errors, f"case {cid}: result {rid}")


def load_cases(errors):
    cases = []
    for d in sorted(CASES_DIR.iterdir()):
        if not d.is_dir() or d.name.startswith("_"):
            continue
        f = d / "case.json"
        if not f.exists():
            errors.append(f"case {d.name}: missing case.json")
            continue
        try:
            case = json.loads(f.read_text())
        except json.JSONDecodeError as e:
            errors.append(f"case {d.name}: invalid JSON in case.json ({e})")
            continue
        case["_dir"] = d
        load_sidecars(case, d, errors)
        cases.append(case)
    return cases


def is_todo(v):
    return not isinstance(v, str) or not v.strip() or v.strip().upper().startswith("TODO")


def validate(cases, allow_todo, errors):
    bib_keys = set(re.findall(r"@\w+\{([^,\s]+)\s*,", REFERENCES_BIB.read_text()))
    seen_orders = {}
    seen_result_ids = {}
    seen_labels = {}
    seen_uids = {}
    prior_uid = committed_uid_bindings()
    prior_result = {uid: rid for rid, uid in prior_uid.items()}

    for c in cases:
        cid = c.get("id", c["_dir"].name)

        def err(msg):
            errors.append(f"case {cid}: {msg}")

        if c.get("id") != c["_dir"].name:
            err(f'id "{c.get("id")}" does not equal directory name "{c["_dir"].name}"')
        for field in ("title", "status", "results", "credits", "verify", "artifacts"):
            if field not in c:
                err(f"missing required field {field!r}")
        status = c.get("status")
        if status not in ("refuted", "withheld"):
            err(f'status must be "refuted" or "withheld", got {status!r}')

        if status == "refuted":
            order = c.get("order")
            if not isinstance(order, int) or order < 1:
                err("refuted case needs a positive integer 'order'")
            elif order in seen_orders:
                err(f"order {order} already used by case {seen_orders[order]}")
            else:
                seen_orders[order] = cid
            dossier = c.get("dossier")
            if not dossier:
                err("refuted case needs a 'dossier' file")
            elif not (c["_dir"] / dossier).exists():
                err(f"dossier file {dossier} does not exist")
            group = c.get("group")
            if group is not None and group not in GROUPS:
                err(f"group {group!r} not one of {sorted(GROUPS)}")
            ctx = c.get("context_tex")
            if ctx is not None and (is_todo(ctx) or not balanced_braces(ctx)):
                err(
                    f"{c.get('_context_file', 'context')} is TODO, empty, or has "
                    "unbalanced braces"
                )
        elif status == "withheld":
            if is_todo(c.get("withheld_reason")):
                err("withheld case needs a non-empty 'withheld_reason'")
            if c.get("order") is not None:
                err("withheld case must not have an 'order'")
            paper = c.get("paper")
            if paper and not (c["_dir"] / paper).exists():
                err(f"paper file {paper} does not exist")

        for key in c.get("bib_keys", []):
            if key not in bib_keys:
                err(f"bib key {key!r} not found in tex/references.bib")

        results = c.get("results") or []
        if not results:
            err("needs at least one entry in 'results'")
        dossier_text = ""
        if status == "refuted" and c.get("dossier") and (c["_dir"] / c["dossier"]).exists():
            dossier_text = (c["_dir"] / c["dossier"]).read_text()
        for r in results:
            rid = r.get("id")
            if not rid:
                err("result missing 'id'")
                continue
            if rid in seen_result_ids:
                err(f"result id {rid!r} already used by case {seen_result_ids[rid]}")
            seen_result_ids[rid] = cid

            uid = r.get("uid")
            if is_todo(uid):
                err(
                    f"result {rid}: missing 'uid'; mint one with "
                    "`python tools/new_case.py --mint-uid`"
                )
            elif not UID_RE.match(uid):
                err(
                    f"result {rid}: uid {uid!r} must be {UID_LEN} characters from "
                    "the Crockford base32 alphabet"
                )
            else:
                if uid in seen_uids:
                    err(f"result {rid}: uid {uid} already used by result {seen_uids[uid]}")
                seen_uids[uid] = rid
                # A uid names one refuted statement permanently: it may neither be
                # repointed at a different result nor swapped out for a new value.
                if rid in prior_uid and prior_uid[rid] != uid:
                    err(
                        f"result {rid}: uid changed from {prior_uid[rid]} to {uid}; "
                        "uids are immutable once published"
                    )
                if uid in prior_result and prior_result[uid] != rid:
                    err(
                        f"result {rid}: uid {uid} is already bound to result "
                        f"{prior_result[uid]}; uids are never reused"
                    )
            for field in ("statement_tex", "class", "certificate_level", "certificate_tex"):
                if is_todo(r.get(field)):
                    err(f"result {rid}: missing or TODO field {field!r}")
            if r.get("class") not in CLASSES:
                err(f"result {rid}: class {r.get('class')!r} not one of {sorted(CLASSES)}")
            if r.get("certificate_level") not in CERTIFICATE_LEVELS:
                err(
                    f"result {rid}: certificate_level {r.get('certificate_level')!r} "
                    f"not one of {sorted(CERTIFICATE_LEVELS)}"
                )
            for field in ("statement_tex", "certificate_tex"):
                v = r.get(field)
                if isinstance(v, str) and not balanced_braces(v):
                    err(f"result {rid}: unbalanced braces in {field}")
            prov = r.get("provenance") or {}
            if status == "refuted":
                if is_todo(prov.get("statement_tex")) or is_todo(prov.get("source_tex")):
                    if allow_todo:
                        print(
                            f"warning: case {cid}: result {rid} has no original statement "
                            f"in provenance",
                            file=sys.stderr,
                        )
                    else:
                        err(
                            f"result {rid}: provenance needs source_tex, and the statement "
                            f"as originally posed in {r.get('_statement_file', 'its .tex file')} "
                            f"(run with --allow-todo during migration)"
                        )
                else:
                    if prov.get("fidelity") not in FIDELITIES:
                        err(
                            f"result {rid}: provenance.fidelity {prov.get('fidelity')!r} "
                            f"not one of {sorted(FIDELITIES)}"
                        )
                    for field in ("statement_tex", "source_tex"):
                        if not balanced_braces(prov[field]):
                            err(f"result {rid}: unbalanced braces in provenance.{field}")

            label = r.get("theorem_label")
            if status == "refuted":
                if not label:
                    err(f"result {rid}: refuted result needs a theorem_label")
                else:
                    if label in seen_labels:
                        err(f"result {rid}: theorem_label {label!r} already used by {seen_labels[label]}")
                    seen_labels[label] = cid
                    if f"\\label{{{label}}}" not in dossier_text:
                        err(f"result {rid}: \\label{{{label}}} not found in {c.get('dossier')}")

        # Credits are validated per result on the merged block, so a result that
        # overrides only 'found_by' still inherits -- and still has to have -- the
        # rest.  A case-level block alone is never enough to pass.
        for r in c.get("results") or []:
            rid = r.get("id") or "?"
            unknown = set(r.get("credits") or {}) - CREDIT_ROLES
            if unknown:
                err(f"result {rid}: unknown credits key(s) {sorted(unknown)}")
            eff = effective_credits(c, r)
            for role in ("posed_by", "formalized_by", "audited_by", "contributed_by"):
                if is_todo(eff.get(role)):
                    err(f"result {rid}: credits.{role} is missing or TODO")
            finders = found_by_list(eff)
            if not finders:
                err(f"result {rid}: credits.found_by is empty")
            for f in finders:
                if not isinstance(f, dict):
                    err(f"result {rid}: each credits.found_by entry must be an object")
                    continue
                model, date = f.get("model"), f.get("date")
                if is_todo(model) or is_todo(date):
                    if allow_todo:
                        print(
                            f"warning: case {cid}: result {rid}: credits.found_by has TODO values",
                            file=sys.stderr,
                        )
                    else:
                        err(
                            f"result {rid}: credits.found_by needs a real model and date "
                            "(run with --allow-todo during migration)"
                        )
                elif not DATE_RE.match(date):
                    err(
                        f"result {rid}: credits.found_by.date {date!r} must match "
                        "YYYY-MM or YYYY-MM-DD"
                    )

        verify = c.get("verify") or {}
        py = verify.get("python")
        if not py:
            err("verify.python is required")
        elif not (c["_dir"] / py).exists():
            err(f"verify.python file {py} does not exist")
        for s in verify.get("sage", []):
            if not (c["_dir"] / s).exists():
                err(f"verify.sage file {s} does not exist")

        for a in c.get("artifacts", []):
            if is_todo(a.get("description")):
                err(f"artifact {a.get('file')}: missing or TODO description")

    # A group is emitted as a single section, so its members must be adjacent in
    # 'order'; otherwise the section heading would be repeated.
    seen_groups = set()
    previous = None
    ordered = [c for c in cases if c.get("status") == "refuted" and isinstance(c.get("order"), int)]
    for c in sorted(ordered, key=lambda c: c["order"]):
        group = c.get("group")
        if group != previous and group in seen_groups:
            errors.append(f"case {c['id']}: group {group!r} is not contiguous in 'order'")
        seen_groups.add(group)
        previous = group


def refuted_in_order(cases):
    return sorted((c for c in cases if c["status"] == "refuted"), key=lambda c: c["order"])


def withheld_sorted(cases):
    return sorted((c for c in cases if c["status"] == "withheld"), key=lambda c: c["id"])


def gen_ledger(cases):
    # Every admitted row is a disproof, so the table carries no status column.
    lines = [
        GENERATED_HEADER + r"\section{Audited archive ledger}",
        "",
        r"\begin{longtable}{@{}p{0.46\textwidth}p{0.50\textwidth}@{}}",
        r"\caption{Admitted session-derived disproofs.}\label{tab:ledger}\\",
        r"\toprule",
        r"Formal statement & Certificate \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Formal statement & Certificate \\",
        r"\midrule",
        r"\endhead",
    ]
    for c in refuted_in_order(cases):
        for r in c["results"]:
            # Point at the theorem, not the section: a grouped case puts several
            # results under one section, so a section reference would send
            # different rows to the same place.  The statement itself is left
            # unlinked -- its \cite already carries the reader to the source.
            ref = f" (Thm.~\\ref{{{r['theorem_label']}}})" if r.get("theorem_label") else ""
            lines.append(f"{r['statement_tex']} & {r['certificate_tex']}{ref}\\\\")
    lines += [r"\bottomrule", r"\end{longtable}", ""]
    return "\n".join(lines)


def effective_credits(c, r):
    """The case credits with this result's overrides applied, key by key.

    Attribution belongs to the result, not the directory: one case may bundle
    two refuted statements found by different models in different sessions.  The
    merge is partial so that a result differing only in 'found_by' does not have
    to restate who posed, formalized, or audited it.
    """
    merged = dict(c.get("credits") or {})
    merged.update(r.get("credits") or {})
    return merged


def found_by_list(credits):
    """'found_by' normalised to a list; one finder may be written as an object."""
    found = credits.get("found_by") or []
    return found if isinstance(found, list) else [found]


def found_by_str(credits):
    """Finders rendered for prose: 'M (2026-07)' or 'M (2026-07) and N (2026-08)'."""
    return " and ".join(f"{f.get('model')} ({f.get('date')})" for f in found_by_list(credits))


def credit_line(cr):
    parts = [
        f"Posed by {cr['posed_by']}",
        f"counterexample found by {found_by_str(cr)}",
        f"formalized by {cr['formalized_by']}",
        f"audited by {cr['audited_by']}",
    ]
    if cr.get("contributed_by") and cr["contributed_by"] != cr["formalized_by"]:
        parts.append(f"contributed by {cr['contributed_by']}")
    return "; ".join(parts) + "."


def credit_blocks(c):
    """One credit line for the case, or one per result when they disagree.

    A single line across bundled results would assert something false about one
    of them as soon as their finders differ.
    """
    per = [(r, effective_credits(c, r)) for r in c["results"]]
    if all(e == per[0][1] for _, e in per):
        return [f"\\dossiercredits{{{credit_line(per[0][1])}}}"]
    out = []
    for r, e in per:
        ref = f"\\Cref{{{r['theorem_label']}}}" if r.get("theorem_label") else r["id"]
        out.append(f"\\dossiercredits{{{ref}: {credit_line(e)}}}")
    return out


def problem_blocks(c):
    """Quote each refuted statement as originally posed, ahead of the dossier."""
    out = []
    for r in c["results"]:
        prov = r.get("provenance") or {}
        if is_todo(prov.get("statement_tex")) or is_todo(prov.get("source_tex")):
            continue
        qualifier = "" if prov.get("fidelity") == "verbatim" else ", paraphrased"
        out.append(
            "\n".join(
                [
                    f"\\begin{{problem}}[As posed{qualifier}: {prov['source_tex']}]",
                    prov["statement_tex"],
                    r"\end{problem}",
                ]
            )
        )
    return out


def gen_dossiers(cases):
    """One section per case, except that grouped cases share one section."""
    blocks = []
    open_group = None
    for c in refuted_in_order(cases):
        title = c.get("title_tex") or c["title"]
        group = c.get("group")
        if group is None:
            heading = f"\\section{{{title}}}"
        else:
            if group != open_group:
                blocks.append(f"\\section{{{GROUPS[group]}}}")
            heading = f"\\subsection{{{title}}}"
        open_group = group
        # Our own setup prose, so the quoted statement can be read without the
        # source at hand; it precedes the quotes and stays outside their boxes.
        context = [c["context_tex"]] if c.get("context_tex") else []
        blocks.append(
            "\n".join(
                [heading]
                + credit_blocks(c)
                + context
                + problem_blocks(c)
                + [f"\\input{{../counterexamples/{c['id']}/{c['dossier']}}}"]
            )
        )
    return GENERATED_HEADER + "\n" + "\n\n".join(blocks) + "\n"


def gen_registry(cases):
    entries = []
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            entries.append((c, r, n))
    for c in withheld_sorted(cases):
        for r in c["results"]:
            entries.append((c, r, None))
    out = []
    for c, r, ledger_no in entries:
        out.append(
            {
                "uid": r.get("uid"),
                "result_id": r["id"],
                "case": c["id"],
                "title": c["title"],
                "status": c["status"],
                "ledger_no": ledger_no,
                "withheld_reason": c.get("withheld_reason"),
                "class": r["class"],
                "certificate_level": r["certificate_level"],
                "certificate_tex": r["certificate_tex"],
                "theorem_label": r.get("theorem_label"),
                "provenance": r.get("provenance"),
                # Always a list here, whatever the case.json shorthand was: the
                # registry is the machine-readable artifact, so its shapes are
                # uniform even when the authoring format is permissive.
                "credits": {**effective_credits(c, r), "found_by": found_by_list(effective_credits(c, r))},
                "verify": c["verify"],
            }
        )
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


ACCENTS = {
    r"\"a": "ä", r"\"o": "ö", r"\"u": "ü", r"\"e": "ë",
    r"\'a": "á", r"\'e": "é", r"\'i": "í", r"\'o": "ó", r"\'u": "ú",
    r"\^a": "â", r"\^e": "ê", r"\^o": "ô", r"\~n": "ñ",
    r"\c{s}": "ş", r"\c{c}": "ç", r"\c{S}": "Ş", r"\c{C}": "Ç",
    r"\"{a}": "ä", r"\"{o}": "ö", r"\"{u}": "ü", r"\'{e}": "é",
}
TEX_SUBS = [
    (re.compile(r"\\cite[a-z]*(?:\[[^\]]*\])*\{[^}]*\}"), ""),
    (re.compile(r"\\path\{([^}]*)\}"), r"`\1`"),
    (re.compile(r"\\emph\{([^}]*)\}"), r"*\1*"),
    (re.compile(r"\\S"), "§"),
    (re.compile(r"--"), "–"),
    (re.compile(r"~"), " "),
    (re.compile(r"\s+"), " "),
    (re.compile(r"\s+([,.;])"), r"\1"),
    (re.compile(r",\s*$"), ""),
]


def tex_to_markdown(s, errors, where):
    """Render a short LaTeX fragment as plain markdown for the README table.

    Deliberately narrow: it handles the constructs the metadata actually uses
    and reports anything left over, so an unhandled macro fails the build
    instead of leaking raw LaTeX into the README.
    """
    for tex, ch in ACCENTS.items():
        s = s.replace(tex, ch)
    for pattern, repl in TEX_SUBS:
        s = pattern.sub(repl, s)
    s = s.strip()
    leftover = set(re.findall(r"\\[A-Za-z]+|[{}]", s))
    if leftover:
        errors.append(
            f"{where}: unhandled LaTeX {sorted(leftover)} in {s!r}; "
            f"extend TEX_SUBS in tools/build.py"
        )
    return s


def source_cell(c, r, errors):
    """Link to where the statement was posed, so a reader can check it."""
    prov = r.get("provenance") or {}
    where = f"case {c['id']}, result {r['id']}"
    if is_todo(prov.get("source_tex")):
        posed = tex_to_markdown(effective_credits(c, r)["posed_by"], errors, where)
        return f"{posed} — statement TODO"
    label = tex_to_markdown(prov["source_tex"], errors, where)
    url = prov.get("url")
    return f"[{label}]({url})" if url else label


def gen_readme_table(cases, errors):
    lines = [
        "| No. | Case | Status | Posed in | Certificate | Found by |",
        "|---|---|---|---|---|---|",
    ]
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            lines.append(
                f"| {n} | [{r['id']}](counterexamples/{c['id']}/) | refuted "
                f"| {source_cell(c, r, errors)} | {r['certificate_level']} "
                f"| {found_by_str(effective_credits(c, r))} |"
            )
    for c in withheld_sorted(cases):
        for r in c["results"]:
            lines.append(
                f"| — | [{r['id']}](counterexamples/{c['id']}/) | withheld "
                f"| {source_cell(c, r, errors)} | {r['certificate_level']} "
                f"| {found_by_str(effective_credits(c, r))} |"
            )
    return "\n".join(lines)


def splice_readme(table):
    text = README.read_text()
    if TABLE_BEGIN not in text or TABLE_END not in text:
        fail([f"README.md: markers {TABLE_BEGIN} / {TABLE_END} not found; refusing to guess"])
    head, rest = text.split(TABLE_BEGIN, 1)
    _, tail = rest.split(TABLE_END, 1)
    return head + TABLE_BEGIN + "\n" + table + "\n" + TABLE_END + tail


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--allow-todo", action="store_true", help="tolerate TODO found_by values")
    args = parser.parse_args()

    errors = []
    cases = load_cases(errors)
    validate(cases, args.allow_todo, errors)
    if errors:
        fail(errors)

    readme_table = gen_readme_table(cases, errors)
    if errors:
        fail(errors)

    outputs = {
        GENERATED_DIR / "ledger.tex": gen_ledger(cases),
        GENERATED_DIR / "dossiers.tex": gen_dossiers(cases),
        REGISTRY: gen_registry(cases),
        README: splice_readme(readme_table),
    }

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in outputs.items()
            if not path.exists() or path.read_text() != content
        ]
        if stale:
            fail([f"stale generated file: {p} (run python tools/build.py)" for p in stale])
        print("generated files up to date")
        return

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content)
        print("wrote", path.relative_to(ROOT))


if __name__ == "__main__":
    main()
