#!/usr/bin/env python3
"""Validate each counterexample's case.json + case.tex and generate the rest.

Every case is two files: case.json (machine facts -- ids, uid, enums, dates,
urls) and case.tex (everything written in LaTeX, in \\begin{cx...} regions this
script extracts).  No LaTeX belongs in the JSON.

Generated (checked in; never edit by hand):
  tex/generated/cases.tex      the paper's case list: per-case metadata
                               (heading level, theorem labels, fidelity) and an
                               \\input of each case.tex, in ledger order.  The
                               typesetting itself is tex/cxcase.sty's job
  registry.json                flattened machine-readable registry (all cases,
                               including withheld ones)
  README.md                    case table between the BEGIN/END CASE TABLE markers

Usage:
  python tools/build.py                validate and regenerate
  python tools/build.py --check        fail (exit 1) if generated files are stale
  python tools/build.py --allow-todo   tolerate TODO found_by values (migration only)

Stdlib only. All validation errors are collected and reported together.
"""
from __future__ import annotations

import argparse
import json
import re
import secrets
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
CASES_DIR = ROOT / "counterexamples"
GENERATED_DIR = ROOT / "tex" / "generated"
REFERENCES_BIB = ROOT / "tex" / "references.bib"
README = ROOT / "README.md"
REGISTRY = ROOT / "registry.json"
# Hand-written, never generated: the maintainer edits this table row by row.
# build.py only checks that it still covers every admitted result.
LEDGER_TEX = ROOT / "tex" / "ledger.tex"

CLASSES = {
    "published theorem",
    "published conjecture",
    "external conjecture",
    "external formal problem",
    "user formal problem",
}
CERTIFICATE_LEVELS = {"exact", "computer-assisted"}
# How faithfully result.provenance.statement_tex reproduces the source.  Only
# "verbatim" is rendered as a quotation of the original; "paraphrase" is labelled
# as such in the paper so a restatement is never passed off as the original.
FIDELITIES = {"verbatim", "paraphrase"}
# Cases sharing a group key are emitted as subsections of one common section
# instead of one section each; their 'order' values must be consecutive.
GROUPS = {
    "aim": "Borcea--Br\\\"and\\'en AIM problems",
    "amsel": "Simons workshop open questions",
}
# Cases carrying "appendix": true are typeset in the hand-written appendix
# tex/09-additional.tex instead of in the body, and collapse to a single ledger
# row per source.  That file owns the heading and every word of prose; what is
# generated is only the two lists it \inputs.
DATE_RE = re.compile(r"^\d{4}-\d{2}(-\d{2})?$")
# Immutable per-result identity, and the primary key of registry.json.  The
# alphabet is Crockford base32 -- no I, L, O or U -- so a uid survives being
# read aloud or retyped, and cannot spell a word by accident.  It is random
# rather than derived from the case, because a content-derived key would change
# every time a statement was corrected, which is the opposite of identity.
#
# A uid is never cited: humans cite the result id.  This exists so that renaming
# a result later does not break a database row pointing at it.
CREDIT_ROLES = {"posed_by", "found_by", "formalized_by", "audited_by", "contributed_by"}
UID_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
UID_LEN = 8
UID_RE = re.compile(rf"^[{UID_ALPHABET}]{{{UID_LEN}}}$")


def mint_uid():
    return "".join(secrets.choice(UID_ALPHABET) for _ in range(UID_LEN))


def committed_uid_bindings():
    """Map result_id -> uid as of the registry currently on disk.

    registry.json is generated, so this is the binding that last survived
    review; comparing new metadata against it is what makes a uid immutable in
    practice rather than only by convention.
    """
    if not REGISTRY.exists():
        return {}
    try:
        rows = json.loads(REGISTRY.read_text())
    except json.JSONDecodeError:
        return {}
    return {r["result_id"]: r["uid"] for r in rows if isinstance(r, dict) and r.get("uid")}
GENERATED_HEADER = "% GENERATED by tools/build.py -- do not edit\n"
TABLE_BEGIN = "<!-- BEGIN CASE TABLE -->"
TABLE_END = "<!-- END CASE TABLE -->"
# The README's headline counts are generated for the same reason the table is:
# a hand-typed "12 refuted" is one admitted case away from being false.
BADGES_BEGIN = "<!-- BEGIN COUNT BADGES -->"
BADGES_END = "<!-- END COUNT BADGES -->"
BADGE_COLOR = "0b7285"


def fail(errors):
    for e in errors:
        print("error:", e, file=sys.stderr)
    sys.exit(1)


# Everything the generator is allowed to overwrite.  README.md is on the list
# only because splice_readme() rewrites two marker-delimited regions of it and
# preserves the rest verbatim; every other word in that file is hand-written.
MACHINE_OWNED = (GENERATED_DIR, REGISTRY, README)


def machine_owned(path):
    """True if build.py may write `path`.

    The archive's rule is that a file is generated or it is the maintainer's,
    never both, and that adoption is one-way: once prose is hand-written, no
    generator reclaims it.  This is the enforcement of that rule; the
    documentation of it lives in /AGENTS.md.
    """
    path = path.resolve()
    return any(path == owned or owned in path.parents for owned in MACHINE_OWNED)


def balanced_braces(s):
    depth = 0
    for ch in s:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                return False
    return depth == 0


# One case, one prose file: everything an author writes in LaTeX lives in
# case.tex, delimited by these environments, and case.json holds only machine
# facts.  Editing a counterexample then means reading one file top to bottom
# instead of four, which is where consistency between the notation, the quoted
# statement and the proof actually gets lost.
#
# CASE_ENVS take no argument; RESULT_ENVS take the result id, since one case may
# refute several statements.  cxcredits is both: bare for the case, with an id
# for a result whose attribution differs.
CASE_ENVS = {"cxcontext", "cxrefutation"}
RESULT_ENVS = {"cxsource", "cxstatement", "cxsummary", "cxcertificate"}
ALL_ENVS = CASE_ENVS | RESULT_ENVS | {"cxcredits"}
# cxrefutation may be split into several regions, whose bodies are one region in
# file order.  A case refuting more than one statement reads better with each
# quote box standing next to the theorem that answers it, and a quote box is a
# cxstatement -- a region, which may not nest.  So the refutation closes before
# the next statement and reopens after it.  Every other region stays once-only:
# two cxsummary{r} are a mistake, two halves of a refutation are a layout.
REPEATABLE_ENVS = {"cxrefutation"}
# The RESULT_ENVS take their result id as a mandatory {arg}; cxcredits takes it
# as LaTeX's optional [arg], because a bare \begin{cxcredits} has to stay legal
# for the common case of one attribution per case.  Accept either spelling here
# so the per-result form documented in _template/case.tex actually parses.
BEGIN_RE = re.compile(r"^\s*\\begin\{(cx[a-z]+)\}(?:\{([^}]*)\}|\[([^\]]*)\])?\s*$")
END_RE = re.compile(r"^\s*\\end\{(cx[a-z]+)\}\s*$")
# Credit roles as they are written in case.tex.  \foundby takes two arguments
# and may repeat; a witness can take more than one model or more than one
# session to reach.
CREDIT_MACROS = {
    "posedby": "posed_by",
    "formalizedby": "formalized_by",
    "auditedby": "audited_by",
    "contributedby": "contributed_by",
}


def read_macro_args(s, i, n):
    """Read n brace groups starting at s[i], honouring nesting.  -> (args, end)."""
    args = []
    for _ in range(n):
        while i < len(s) and s[i].isspace():
            i += 1
        if i >= len(s) or s[i] != "{":
            return None, i
        depth, start = 0, i + 1
        while i < len(s):
            if s[i] == "{":
                depth += 1
            elif s[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        if i >= len(s):
            return None, i
        args.append(s[start:i])
        i += 1
    return args, i


def parse_credits(body, errors, where):
    """A cxcredits body: one macro per role, \\foundby repeatable."""
    credits, i = {}, 0
    while True:
        j = body.find("\\", i)
        if j < 0:
            break
        m = re.match(r"\\([a-z]+)", body[j:])
        if not m:
            i = j + 1
            continue
        name = m.group(1)
        if name == "foundby":
            args, i = read_macro_args(body, j + len(m.group(0)), 2)
            if args is None:
                errors.append(f"{where}: \\foundby needs two arguments: {{model}}{{YYYY-MM}}")
                break
            credits.setdefault("found_by", []).append({"model": args[0], "date": args[1]})
        elif name in CREDIT_MACROS:
            args, i = read_macro_args(body, j + len(m.group(0)), 1)
            if args is None:
                errors.append(f"{where}: \\{name} needs one argument")
                break
            credits[CREDIT_MACROS[name]] = args[0]
        else:
            errors.append(
                f"{where}: unknown credit macro \\{name}; expected "
                f"{sorted('\\\\' + k for k in ['foundby', *CREDIT_MACROS])}"
            )
            i = j + len(m.group(0))
    return credits


def parse_title(text, errors, where):
    """The \\cxtitle{...} line.  A title is one line, so it is a macro, not a
    region -- and a run-in subsection heading issued from inside an environment
    would be dropped by LaTeX anyway (see tex/cxcase.sty)."""
    i = text.find("\\cxtitle")
    if i < 0:
        errors.append(f"{where}: no \\cxtitle{{...}}")
        return ""
    args, _ = read_macro_args(text, i + len("\\cxtitle"), 1)
    if args is None:
        errors.append(f"{where}: \\cxtitle needs one braced argument")
        return ""
    return args[0].strip()


def parse_case_tex(text, errors, where):
    """case.tex -> {(env, arg): body}.

    Regions are found line by line: a \\begin{cx...} and its \\end must each sit
    alone on a line.  Deliberately literal -- a prose file whose structure needs
    a LaTeX parser to recover is a prose file whose structure an author cannot
    see either.  Whole-line comments are dropped from bodies, so the template
    can carry its guidance as comments without it reaching the paper or hiding
    an unfilled TODO.
    """
    regions, open_env, arg, body = {}, None, None, []
    for lineno, line in enumerate(text.splitlines(), 1):
        begin = BEGIN_RE.match(line)
        end = END_RE.match(line)
        if begin:
            name = begin.group(1)
            if open_env:
                errors.append(
                    f"{where}: line {lineno}: \\begin{{{name}}} inside {open_env}; "
                    "these regions may not nest"
                )
                return regions
            if name not in ALL_ENVS:
                errors.append(f"{where}: line {lineno}: unknown region {name}; expected one of {sorted(ALL_ENVS)}")
            open_env, arg, body = name, begin.group(2) or begin.group(3) or "", []
        elif end:
            name = end.group(1)
            if name != open_env:
                errors.append(f"{where}: line {lineno}: \\end{{{name}}} does not close {open_env or 'anything'}")
                return regions
            key = (open_env, arg)
            chunk = "\n".join(body).strip("\n")
            if key in regions:
                if open_env in REPEATABLE_ENVS:
                    chunk = f"{regions[key]}\n\n{chunk}"
                else:
                    label = f"{open_env}{{{arg}}}" if arg else open_env
                    errors.append(f"{where}: {label} appears twice")
            regions[key] = chunk
            open_env = None
        elif open_env and not line.lstrip().startswith("%"):
            body.append(line)
    if open_env:
        errors.append(f"{where}: \\begin{{{open_env}}} is never closed")
    return regions


def load_prose(case, d, errors):
    """Fill the fields the rest of the build expects from the case's one .tex file.

    Downstream code still sees title_tex / context_tex / statement_tex /
    certificate_tex / credits exactly as when they were JSON keys; only the
    place an author writes them has changed.
    """
    cid = case.get("id", d.name)
    where = f"case {cid}"
    stale = [k for k in ("title_tex", "dossier", "context", "credits") if k in case]
    for r in case.get("results") or []:
        stale += [f"results.{k}" for k in ("statement_tex", "certificate_tex", "credits") if k in r]
        prov = r.get("provenance") or {}
        stale += [f"provenance.{k}" for k in ("statement", "statement_tex", "source_tex") if k in prov]
    if stale:
        errors.append(
            f"{where}: {sorted(set(stale))} no longer belong in case.json; that prose "
            f"lives in {case.get('prose', 'case.tex')} as a cx... region"
        )

    name = case.get("prose", "case.tex")
    path = d / name
    if not path.exists():
        errors.append(f"{where}: prose file {name!r} does not exist")
        return
    text = path.read_text()
    regions = parse_case_tex(text, errors, f"{where} ({name})")
    title = parse_title(text, errors, f"{where} ({name})")
    ids = {r.get("id") for r in case.get("results") or []}
    for (env, arg), body in regions.items():
        if env in RESULT_ENVS and arg not in ids:
            errors.append(f"{where}: {env}{{{arg}}} names no result in case.json ({sorted(ids)})")
        if env in CASE_ENVS and arg:
            errors.append(f"{where}: {env} takes no argument, got {{{arg}}}")

    case["title_tex"] = title or case.get("title")
    if ("cxcontext", "") in regions:
        case["context_tex"] = regions[("cxcontext", "")]
    case["_refutation"] = regions.get(("cxrefutation", ""), "")
    case["credits"] = parse_credits(regions.get(("cxcredits", ""), ""), errors, f"{where} credits")
    for r in case.get("results") or []:
        rid = r.get("id")
        r["statement_tex"] = regions.get(("cxsummary", rid), "")
        r["certificate_tex"] = regions.get(("cxcertificate", rid), "")
        # Rebuilt rather than updated, so the registry's provenance fields keep a
        # fixed order however case.json happens to spell it.
        prov = r.get("provenance") or {}
        r["provenance"] = {
            "source_tex": regions.get(("cxsource", rid), ""),
            **{k: prov[k] for k in ("url", "retrieved", "fidelity") if k in prov},
            "statement_tex": regions.get(("cxstatement", rid), ""),
        }
        if ("cxcredits", rid) in regions:
            r["credits"] = parse_credits(regions[("cxcredits", rid)], errors, f"{where}: result {rid} credits")


def load_cases(errors):
    cases = []
    for d in sorted(CASES_DIR.iterdir()):
        if not d.is_dir() or d.name.startswith("_"):
            continue
        f = d / "case.json"
        if not f.exists():
            errors.append(f"case {d.name}: missing case.json")
            continue
        try:
            case = json.loads(f.read_text())
        except json.JSONDecodeError as e:
            errors.append(f"case {d.name}: invalid JSON in case.json ({e})")
            continue
        case["_dir"] = d
        load_prose(case, d, errors)
        cases.append(case)
    return cases


def is_todo(v):
    return not isinstance(v, str) or not v.strip() or v.strip().upper().startswith("TODO")


def validate(cases, allow_todo, errors):
    bib_keys = set(re.findall(r"@\w+\{([^,\s]+)\s*,", REFERENCES_BIB.read_text()))
    seen_orders = {}
    seen_result_ids = {}
    seen_labels = {}
    seen_uids = {}
    seen_former_ids = {}
    prior_uid = committed_uid_bindings()
    prior_result = {uid: rid for rid, uid in prior_uid.items()}

    for c in cases:
        cid = c.get("id", c["_dir"].name)

        def err(msg):
            errors.append(f"case {cid}: {msg}")

        if c.get("id") != c["_dir"].name:
            err(f'id "{c.get("id")}" does not equal directory name "{c["_dir"].name}"')
        for field in ("title", "status", "results", "credits", "verify", "artifacts"):
            if field not in c:
                err(f"missing required field {field!r}")
        status = c.get("status")
        if status not in ("refuted", "withheld"):
            err(f'status must be "refuted" or "withheld", got {status!r}')

        if status == "refuted":
            order = c.get("order")
            if not isinstance(order, int) or order < 1:
                err("refuted case needs a positive integer 'order'")
            elif order in seen_orders:
                err(f"order {order} already used by case {seen_orders[order]}")
            else:
                seen_orders[order] = cid
            if is_todo(c.get("_refutation")):
                err("the cxrefutation region is missing or still TODO")
            if is_todo(c.get("title_tex")):
                err("the cxtitle region is missing or still TODO")
            group = c.get("group")
            if group is not None and group not in GROUPS:
                err(f"group {group!r} not one of {sorted(GROUPS)}")
            appendix = c.get("appendix")
            if appendix is not None and not isinstance(appendix, bool):
                err(f"'appendix' must be true or false, not {appendix!r}")
            brief = c.get("brief")
            if brief is not None and not isinstance(brief, bool):
                err(f"'brief' must be true or false, not {brief!r}")
            if brief and not appendix:
                err("'brief' is only meaningful on a case that is also \"appendix\": true")
            if brief:
                # A brief case's ledger_label is typeset by \cxbriefitem, not
                # just spliced into README.md, so plain text now has to mean
                # plain text: an unescaped & or % would break the paper build
                # with an error pointing at a generated file.
                for r in c.get("results") or []:
                    bad = set(r.get("ledger_label") or "") & set("&%#_$}{~^\\")
                    if bad:
                        err(
                            f"result {r.get('id')}: ledger_label of a brief case is typeset "
                            f"as LaTeX; remove {''.join(sorted(bad))}"
                        )
            if appendix:
                # The collapsed ledger row names the items it stands for, and
                # nothing else in the case records an item number in plain text.
                for r in c.get("results") or []:
                    if is_todo(r.get("ledger_label")):
                        err(
                            f"result {r.get('id')}: an appendix case needs a plain-text "
                            f"'ledger_label' such as 'Problem 4.6', naming the item it "
                            f"refutes in the collapsed ledger row"
                        )
            ctx = c.get("context_tex")
            if ctx is not None and (is_todo(ctx) or not balanced_braces(ctx)):
                err("the cxcontext region is TODO, empty, or has unbalanced braces")
        elif status == "withheld":
            if is_todo(c.get("withheld_reason")):
                err("withheld case needs a non-empty 'withheld_reason'")
            if c.get("order") is not None:
                err("withheld case must not have an 'order'")
            paper = c.get("paper")
            if paper and not (c["_dir"] / paper).exists():
                err(f"paper file {paper} does not exist")

        for key in c.get("bib_keys", []):
            if key not in bib_keys:
                err(f"bib key {key!r} not found in tex/references.bib")

        results = c.get("results") or []
        if not results:
            err("needs at least one entry in 'results'")
        refutation = c.get("_refutation") or ""
        for r in results:
            rid = r.get("id")
            if not rid:
                err("result missing 'id'")
                continue
            if rid in seen_result_ids:
                err(f"result id {rid!r} already used by case {seen_result_ids[rid]}")
            seen_result_ids[rid] = cid
            if rid in seen_former_ids:
                err(
                    f"result id {rid!r} is a former id of result {seen_former_ids[rid]}; "
                    "a name a result was renamed away from is not reused"
                )

            # Every id this result has been known by, oldest first.  A rename is
            # the one thing that would otherwise be indistinguishable from
            # reusing a retired uid, so it is recorded rather than inferred: the
            # uid follows the statement (which is what a uid is for), and the old
            # name stays resolvable through registry.json.
            former_ids = r.get("former_ids") or []
            if not isinstance(former_ids, list) or not all(
                isinstance(x, str) and x.strip() for x in former_ids
            ):
                err("'former_ids' must be a list of the result ids this one was renamed from")
                former_ids = []
            r["former_ids"] = former_ids
            for old in former_ids:
                if old == rid:
                    err(f"result {rid}: lists its own id in 'former_ids'")
                if old in seen_result_ids:
                    err(
                        f"result {rid}: former id {old!r} is the live id of a result in "
                        f"case {seen_result_ids[old]}; a renamed-away name is not reused"
                    )
                if old in seen_former_ids:
                    err(
                        f"result {rid}: former id {old!r} is already claimed by result "
                        f"{seen_former_ids[old]}"
                    )
                seen_former_ids[old] = rid

            uid = r.get("uid")
            if is_todo(uid):
                err(
                    f"result {rid}: missing 'uid'; mint one with "
                    "`python tools/new_case.py --mint-uid`"
                )
            elif not UID_RE.match(uid):
                err(
                    f"result {rid}: uid {uid!r} must be {UID_LEN} characters from "
                    "the Crockford base32 alphabet"
                )
            else:
                if uid in seen_uids:
                    err(f"result {rid}: uid {uid} already used by result {seen_uids[uid]}")
                seen_uids[uid] = rid
                # A uid names one refuted statement permanently: it may neither be
                # repointed at a different result nor swapped out for a new value.
                if rid in prior_uid and prior_uid[rid] != uid:
                    err(
                        f"result {rid}: uid changed from {prior_uid[rid]} to {uid}; "
                        "uids are immutable once published"
                    )
                # ... unless the result was renamed and says so.  Then the uid is
                # not being reused, it is doing its job: the same statement under
                # a new name.  Listing the old id is what separates the two cases,
                # and it is deliberately an explicit claim by the author rather
                # than something inferred from the diff.
                if (
                    uid in prior_result
                    and prior_result[uid] != rid
                    and prior_result[uid] not in former_ids
                ):
                    err(
                        f"result {rid}: uid {uid} is already bound to result "
                        f"{prior_result[uid]}; uids are never reused. If this is a "
                        f"rename, add {prior_result[uid]!r} to this result's "
                        "'former_ids' and the uid will follow the statement"
                    )
            # Name the thing an author edits: two of these are regions of
            # case.tex, two are enums in case.json.
            for field, where in (
                ("statement_tex", f"the cxsummary{{{rid}}} region"),
                ("certificate_tex", f"the cxcertificate{{{rid}}} region"),
                ("class", "case.json 'class'"),
                ("certificate_level", "case.json 'certificate_level'"),
            ):
                if is_todo(r.get(field)):
                    err(f"result {rid}: {where} is missing or still TODO")
            if r.get("class") not in CLASSES:
                err(f"result {rid}: class {r.get('class')!r} not one of {sorted(CLASSES)}")
            if r.get("certificate_level") not in CERTIFICATE_LEVELS:
                err(
                    f"result {rid}: certificate_level {r.get('certificate_level')!r} "
                    f"not one of {sorted(CERTIFICATE_LEVELS)}"
                )
            for field in ("statement_tex", "certificate_tex"):
                v = r.get(field)
                if isinstance(v, str) and not balanced_braces(v):
                    err(f"result {rid}: unbalanced braces in {field}")
            prov = r.get("provenance") or {}
            if status == "refuted":
                if is_todo(prov.get("statement_tex")) or is_todo(prov.get("source_tex")):
                    if allow_todo:
                        print(
                            f"warning: case {cid}: result {rid} has no original statement "
                            f"in provenance",
                            file=sys.stderr,
                        )
                    else:
                        err(
                            f"result {rid}: case.tex needs cxsource{{{rid}}} and cxstatement"
                            f"{{{rid}}}, the statement as originally posed "
                            f"(run with --allow-todo during migration)"
                        )
                else:
                    if prov.get("fidelity") not in FIDELITIES:
                        err(
                            f"result {rid}: provenance.fidelity {prov.get('fidelity')!r} "
                            f"not one of {sorted(FIDELITIES)}"
                        )
                    for field in ("statement_tex", "source_tex"):
                        if not balanced_braces(prov[field]):
                            err(f"result {rid}: unbalanced braces in provenance.{field}")

            label = r.get("theorem_label")
            if status == "refuted":
                if not label:
                    err(f"result {rid}: refuted result needs a theorem_label")
                else:
                    if label in seen_labels:
                        err(f"result {rid}: theorem_label {label!r} already used by {seen_labels[label]}")
                    seen_labels[label] = cid
                    if f"\\label{{{label}}}" not in refutation:
                        err(f"result {rid}: \\label{{{label}}} not found in the cxrefutation region")

        # Credits are validated per result on the merged block, so a result that
        # overrides only \foundby still inherits -- and still has to have -- the
        # rest.  A case-level block alone is never enough to pass.
        for r in c.get("results") or []:
            rid = r.get("id") or "?"
            eff = effective_credits(c, r)
            macro = {v: k for k, v in CREDIT_MACROS.items()}
            for role in ("posed_by", "formalized_by", "audited_by", "contributed_by"):
                if is_todo(eff.get(role)):
                    err(f"result {rid}: cxcredits is missing \\{macro[role]}, or it is TODO")
            finders = found_by_list(eff)
            if not finders:
                err(f"result {rid}: cxcredits has no \\foundby")
            for f in finders:
                model, date = f.get("model"), f.get("date")
                if is_todo(model) or is_todo(date):
                    if allow_todo:
                        print(
                            f"warning: case {cid}: result {rid}: \\foundby has TODO values",
                            file=sys.stderr,
                        )
                    else:
                        err(
                            f"result {rid}: \\foundby needs a real model and date "
                            "(run with --allow-todo during migration)"
                        )
                elif not DATE_RE.match(date):
                    err(
                        f"result {rid}: \\foundby date {date!r} must match "
                        "YYYY-MM or YYYY-MM-DD"
                    )

        verify = c.get("verify") or {}
        py = verify.get("python")
        if not py:
            err("verify.python is required")
        elif not (c["_dir"] / py).exists():
            err(f"verify.python file {py} does not exist")
        for s in verify.get("sage", []):
            if not (c["_dir"] / s).exists():
                err(f"verify.sage file {s} does not exist")

        for a in c.get("artifacts", []):
            if is_todo(a.get("description")):
                err(f"artifact {a.get('file')}: missing or TODO description")

    # A group is emitted as a single section, so its members must be adjacent in
    # 'order'; otherwise the section heading would be repeated.
    seen_groups = set()
    previous = None
    ordered = [c for c in cases if c.get("status") == "refuted" and isinstance(c.get("order"), int)]
    for c in sorted(ordered, key=lambda c: c["order"]):
        group = c.get("group")
        if group != previous and group in seen_groups:
            errors.append(f"case {c['id']}: group {group!r} is not contiguous in 'order'")
        seen_groups.add(group)
        previous = group


def refuted_in_order(cases):
    """Every refuted case, body first and appendix last, each by ledger order.

    The appendix collects cases the archive keeps but does not foreground --
    statements too slight to carry a section of their own, or ones whose public
    resolution belongs to someone else.  They are admitted on exactly the same
    evidence as any other case; only their presentation differs.
    """
    refuted = [c for c in cases if c["status"] == "refuted"]
    return sorted(refuted, key=lambda c: (bool(c.get("appendix")), c["order"]))


def body_in_order(cases):
    return [c for c in refuted_in_order(cases) if not c.get("appendix")]


def appendix_in_order(cases):
    return [c for c in refuted_in_order(cases) if c.get("appendix")]


def appendix_full_in_order(cases):
    """Appendix cases that still earn a dossier of their own."""
    return [c for c in appendix_in_order(cases) if not c.get("brief")]


def brief_in_order(cases):
    """Appendix cases recorded as a one-line entry instead of a dossier.

    A brief case is admitted, verified and registered exactly like any other --
    the same certificate runs in the same `make verify` -- but the paper spends
    a bullet on it rather than a section and a ledger row.  The distinction is
    editorial weight only, which is why nothing here touches registry.json's
    numbering or the README table: those index the archive, not the paper.
    """
    return [c for c in appendix_in_order(cases) if c.get("brief")]


def appendix_batches(cases):
    """Appendix cases collapsed to one ledger row each, keyed by group.

    A batch drawn from one source earns a single row naming that source and the
    items refuted inside it, rather than one row per statement: the ledger still
    counts statements, but the table stops spending four rows on them.  An
    ungrouped appendix case is its own batch.
    """
    batches = []
    for c in appendix_in_order(cases):
        key = c.get("group") or f"__{c['id']}"
        if batches and batches[-1][0] == key:
            batches[-1][1].append(c)
        else:
            batches.append((key, [c]))
    return batches


def withheld_sorted(cases):
    return sorted((c for c in cases if c["status"] == "withheld"), key=lambda c: c["id"])


def effective_credits(c, r):
    """The case credits with this result's overrides applied, key by key.

    Attribution belongs to the result, not the directory: one case may bundle
    two refuted statements found by different models in different sessions.  The
    merge is partial so that a result differing only in 'found_by' does not have
    to restate who posed, formalized, or audited it.
    """
    merged = dict(c.get("credits") or {})
    merged.update(r.get("credits") or {})
    return merged


def found_by_list(credits):
    """'found_by' normalised to a list; one finder may be written as an object."""
    found = credits.get("found_by") or []
    return found if isinstance(found, list) else [found]


def found_by_str(credits):
    """Finders rendered for prose: 'M (2026-07)' or 'M (2026-07) and N (2026-08)'."""
    return " and ".join(f"{f.get('model')} ({f.get('date')})" for f in found_by_list(credits))


def emit_cases(selected, lines, grouped=True):
    """Append the metadata and \\input for each case in `selected` to `lines`.

    Everything typeset comes out of the case files themselves, through the
    environments tex/cxcase.sty defines.  What LaTeX cannot know is metadata --
    where a case sits in the ledger, whether it shares a section with others,
    which theorem label a result carries, and whether its quoted statement is
    the source's own words -- so that is what these files carry.

    `grouped=False` suppresses the per-group headings: the appendix already has
    one heading of its own and does not reissue a section for each source.
    """
    open_group = None
    for c in selected:
        group = c.get("group")
        if grouped and group is not None and group != open_group:
            lines.append(f"\\cxgroup{{{GROUPS[group]}}}")
        open_group = group
        lines.append("")
        lines.append(f"\\cxlevel{{{'subsection' if (group or not grouped) else 'section'}}}")
        for r in c["results"]:
            if r.get("theorem_label"):
                lines.append(f"\\cxtheorem{{{r['id']}}}{{{r['theorem_label']}}}")
            prov = r.get("provenance") or {}
            # A result whose source is not yet recorded is declared pending, so
            # the paper omits the quote box instead of typesetting a TODO.
            if is_todo(prov.get("statement_tex")) or is_todo(prov.get("source_tex")):
                lines.append(f"\\cxpending{{{r['id']}}}")
            elif prov.get("fidelity") in FIDELITIES:
                lines.append(f"\\cx{prov['fidelity']}{{{r['id']}}}")
        lines.append(f"\\input{{../counterexamples/{c['id']}/{c.get('prose', 'case.tex')}}}")
    return lines


def squash(tex):
    """A case region folded onto one line, for a table row or a list item."""
    return " ".join((tex or "").split())


def ledger_row(c, r, n):
    """The row a maintainer can paste into tex/ledger.tex for a new result."""
    statement = squash(r.get("statement_tex"))
    certificate = squash(r.get("certificate_tex"))
    label = r.get("theorem_label") or f"thm:{r['id']}"
    where = "appendix" if c.get("appendix") else "body"
    # \cxn rather than a literal number: the ledger numbers itself, so a pasted
    # row lands correctly wherever it is put and nothing needs renumbering.
    return (f"  % {r['id']} ({where}; generator's ledger position {n})\n"
            f"  \\cxn & {statement} & {certificate}\\ (Thm.~\\ref{{{label}}})\\\\")


def check_ledger(cases, errors):
    """tex/ledger.tex is hand-written; make sure it still covers every result.

    The table's prose, ordering and layout are the maintainer's, so nothing here
    rewrites it.  The one thing a human can silently get wrong is omitting a
    case -- the ledger is the paper's headline claim about how many statements
    fell -- so the build checks coverage and nothing else.  A result is matched
    by its theorem_label appearing in a \\ref, which the row already carries;
    no extra markup is imposed on the file.
    """
    if not LEDGER_TEX.exists():
        errors.append(f"{LEDGER_TEX.relative_to(ROOT)} is missing; it is hand-written, not generated")
        return
    text = LEDGER_TEX.read_text()
    referenced = set(re.findall(r"\\ref\{([^}]*)\}", text))
    known = {}
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            label = r.get("theorem_label") or f"thm:{r['id']}"
            known[label] = (c, r, n)
            if c.get("brief"):
                # A brief case is listed in the appendix instead of the table,
                # so the row must be absent -- and a leftover one is an error
                # rather than a silent duplicate of the bullet.
                if label in referenced:
                    errors.append(
                        f"tex/ledger.tex still has a row for brief result {r['id']}: "
                        f"delete the row referencing \\ref{{{label}}}, or drop "
                        f'"brief" from {c["id"]}/case.json'
                    )
                continue
            if label not in referenced:
                errors.append(
                    f"tex/ledger.tex has no row for result {r['id']}: add one "
                    f"referencing \\ref{{{label}}}. Suggested row:\n{ledger_row(c, r, n)}"
                )
    for label in sorted(referenced - set(known)):
        if label.startswith("thm:"):
            errors.append(
                f"tex/ledger.tex references \\ref{{{label}}}, which names no admitted "
                f"result; delete that row or fix the label"
            )


def gen_cases(cases):
    """The body case list, \\input by main.tex where the sections belong."""
    return "\n".join(emit_cases(body_in_order(cases), [GENERATED_HEADER.rstrip("\n")])) + "\n"


def gen_appendix_cases(cases):
    """The dossiers of the appendix, as a bare list with no heading of its own.

    Two files rather than one, and neither carrying the section heading, so that
    tex/09-additional.tex can put prose before the dossiers, between them and the
    brief list, and after -- which a single generated block would leave nowhere
    to go.  Everything an author writes about the appendix lives there; this is
    only the ordering and the per-case metadata, exactly as in cases.tex.
    """
    lines = [GENERATED_HEADER.rstrip("\n")]
    full = appendix_full_in_order(cases)
    if not full:
        # Still written, so the \input never dangles when the archive happens to
        # have no de-emphasised case that earns a dossier.
        lines.append("% No cases are currently \"appendix\": true without \"brief\": true.")
        return "\n".join(lines) + "\n"
    emit_cases(full, lines, grouped=False)
    return "\n".join(lines) + "\n"


def gen_appendix_brief(cases):
    """The \\cxbriefitem lines of the appendix's brief list, and nothing else.

    No \\begin{itemize} and no lead-in sentence: both are prose decisions, so
    both live in tex/09-additional.tex around the \\input.  Emptying this file is
    not how an entry is removed -- drop "brief" from the case's case.json and it
    goes back to a full subsection and a ledger row.
    """
    lines = [GENERATED_HEADER.rstrip("\n")]
    brief = brief_in_order(cases)
    if not brief:
        lines.append("% No cases are currently marked \"brief\": true.")
        return "\n".join(lines) + "\n"
    for c in brief:
        for r in c["results"]:
            lines.append(
                f"\\cxbriefitem{{{r['ledger_label']}}}"
                f"{{{squash(r.get('statement_tex'))}}}"
                f"{{{squash(r.get('certificate_tex'))}}}"
                f"{{counterexamples/{c['id']}/}}"
            )
    return "\n".join(lines) + "\n"


def gen_registry(cases):
    entries = []
    n = 0
    for c in refuted_in_order(cases):
        for r in c["results"]:
            n += 1
            entries.append((c, r, n))
    for c in withheld_sorted(cases):
        for r in c["results"]:
            entries.append((c, r, None))
    out = []
    for c, r, ledger_no in entries:
        out.append(
            {
                "uid": r.get("uid"),
                "result_id": r["id"],
                # Every id this result has answered to before, so a reference
                # written against an older registry still resolves to the row.
                "former_ids": r.get("former_ids") or [],
                "case": c["id"],
                "title": c["title"],
                "status": c["status"],
                "ledger_no": ledger_no,
                "appendix": bool(c.get("appendix")),
                "brief": bool(c.get("brief")),
                "ledger_label": r.get("ledger_label"),
                "withheld_reason": c.get("withheld_reason"),
                "class": r["class"],
                "certificate_level": r["certificate_level"],
                "certificate_tex": r["certificate_tex"],
                "theorem_label": r.get("theorem_label"),
                "provenance": r.get("provenance"),
                # Always a list here, whatever the case.json shorthand was: the
                # registry is the machine-readable artifact, so its shapes are
                # uniform even when the authoring format is permissive.
                "credits": {**effective_credits(c, r), "found_by": found_by_list(effective_credits(c, r))},
                "verify": c["verify"],
            }
        )
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


ACCENTS = {
    r"\"a": "ä", r"\"o": "ö", r"\"u": "ü", r"\"e": "ë",
    r"\'a": "á", r"\'e": "é", r"\'i": "í", r"\'o": "ó", r"\'u": "ú",
    r"\^a": "â", r"\^e": "ê", r"\^o": "ô", r"\~n": "ñ",
    r"\c{s}": "ş", r"\c{c}": "ç", r"\c{S}": "Ş", r"\c{C}": "Ç",
    r"\"{a}": "ä", r"\"{o}": "ö", r"\"{u}": "ü", r"\'{e}": "é",
}
TEX_SUBS = [
    (re.compile(r"\\cite[a-z]*(?:\[[^\]]*\])*\{[^}]*\}"), ""),
    (re.compile(r"\\path\{([^}]*)\}"), r"`\1`"),
    (re.compile(r"\\emph\{([^}]*)\}"), r"*\1*"),
    (re.compile(r"\\S"), "§"),
    (re.compile(r"--"), "–"),
    (re.compile(r"~"), " "),
    (re.compile(r"\s+"), " "),
    (re.compile(r"\s+([,.;])"), r"\1"),
    (re.compile(r",\s*$"), ""),
]


def tex_to_markdown(s, errors, where):
    """Render a short LaTeX fragment as plain markdown for the README table.

    Deliberately narrow: it handles the constructs the metadata actually uses
    and reports anything left over, so an unhandled macro fails the build
    instead of leaking raw LaTeX into the README.
    """
    for tex, ch in ACCENTS.items():
        s = s.replace(tex, ch)
    for pattern, repl in TEX_SUBS:
        s = pattern.sub(repl, s)
    s = s.strip()
    leftover = set(re.findall(r"\\[A-Za-z]+|[{}]", s))
    if leftover:
        errors.append(
            f"{where}: unhandled LaTeX {sorted(leftover)} in {s!r}; "
            f"extend TEX_SUBS in tools/build.py"
        )
    return s


def source_cell(c, r, errors):
    """Link to where the statement was posed, so a reader can check it."""
    prov = r.get("provenance") or {}
    where = f"case {c['id']}, result {r['id']}"
    if is_todo(prov.get("source_tex")):
        posed = tex_to_markdown(effective_credits(c, r)["posed_by"], errors, where)
        return f"{posed} — statement TODO"
    label = tex_to_markdown(prov["source_tex"], errors, where)
    url = prov.get("url")
    return f"[{label}]({url})" if url else label


def gen_readme_table(cases, errors):
    lines = [
        "| No. | Case | Status | Posed in | Certificate | Found by |",
        "|---|---|---|---|---|---|",
    ]
    n = 0
    for c in body_in_order(cases):
        for r in c["results"]:
            n += 1
            lines.append(
                f"| {n} | [{r['id']}](counterexamples/{c['id']}/) | refuted "
                f"| {source_cell(c, r, errors)} | {r['certificate_level']} "
                f"| {found_by_str(effective_credits(c, r))} |"
            )
    for key, batch in appendix_batches(cases):
        labels = [r.get("ledger_label") for c in batch for r in c["results"]]
        # The row collapses, the count does not: it spans as many ledger numbers
        # as it has statements, so registry.json's ledger_no still resolves here.
        first, n = n + 1, n + len(labels)
        span = str(first) if first == n else f"{first}–{n}"
        levels = sorted({r["certificate_level"] for c in batch for r in c["results"]})
        finders = sorted({found_by_str(effective_credits(c, r))
                          for c in batch for r in c["results"]})
        title = GROUPS[key] if key in GROUPS else batch[0]["title"]
        url = next(
            ((r.get("provenance") or {}).get("url")
             for c in batch for r in c["results"] if (r.get("provenance") or {}).get("url")),
            None,
        )
        where = f"{title} — {', '.join(labels)}"
        cell = f"[{where}]({url})" if url else where
        links = ", ".join(f"[{c['id']}](counterexamples/{c['id']}/)" for c in batch)
        lines.append(
            f"| {span} | {links} | refuted by explicit construction "
            f"| {cell} | {', '.join(levels)} | {', '.join(finders)} |"
        )
    for c in withheld_sorted(cases):
        for r in c["results"]:
            lines.append(
                f"| — | [{r['id']}](counterexamples/{c['id']}/) | withheld "
                f"| {source_cell(c, r, errors)} | {r['certificate_level']} "
                f"| {found_by_str(effective_credits(c, r))} |"
            )
    return "\n".join(lines)


def badge_url(label, message):
    """A shields.io badge path: a literal '-' is doubled, everything else quoted."""
    esc = lambda s: quote(s.replace("-", "--"), safe="")  # noqa: E731
    return f"https://img.shields.io/badge/{esc(label)}-{esc(message)}-{BADGE_COLOR}"


def gen_count_badges(cases):
    """The front-page counts, taken from the ledger rather than from memory."""
    results = [r for c in refuted_in_order(cases) for r in c["results"]]
    body = [r for c in body_in_order(cases) for r in c["results"]]
    extra = [r for c in appendix_in_order(cases) for r in c["results"]]
    levels = Counter(r["certificate_level"] for r in results)
    mix = f"{levels['exact']} exact, {levels['computer-assisted']} interval"
    # Appendix statements are refuted on the same evidence, so they stay in the
    # certificate mix; the headline splits them out only to say which ones the
    # archive foregrounds.
    count = f"{len(body)} refuted" + (f", {len(extra)} additional" if extra else "")
    return "\n".join(
        [
            f"[![counterexamples]({badge_url('counterexamples', count)})]"
            "(#the-cases)",
            f"[![certificates]({badge_url('certificates', mix)})](#the-cases)",
        ]
    )


def splice(text, begin, end, body):
    if begin not in text or end not in text:
        fail([f"README.md: markers {begin} / {end} not found; refusing to guess"])
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return head + begin + "\n" + body + "\n" + end + tail


def splice_readme(table, badges):
    text = splice(README.read_text(), TABLE_BEGIN, TABLE_END, table)
    return splice(text, BADGES_BEGIN, BADGES_END, badges)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--allow-todo", action="store_true", help="tolerate TODO found_by values")
    args = parser.parse_args()

    errors = []
    cases = load_cases(errors)
    validate(cases, args.allow_todo, errors)
    # tex/ledger.tex is not generated, so this is a coverage check rather than a
    # staleness one.  It runs unconditionally: gating it on validate() passing
    # would make it dead code for as long as the baseline carries errors, which
    # is precisely when a missing row is most likely to slip through.
    check_ledger(cases, errors)
    if errors:
        fail(errors)

    readme_table = gen_readme_table(cases, errors)
    if errors:
        fail(errors)

    outputs = {
        GENERATED_DIR / "cases.tex": gen_cases(cases),
        GENERATED_DIR / "appendix-cases.tex": gen_appendix_cases(cases),
        GENERATED_DIR / "appendix-brief.tex": gen_appendix_brief(cases),
        REGISTRY: gen_registry(cases),
        README: splice_readme(readme_table, gen_count_badges(cases)),
    }
    # Ownership guard.  Prose the maintainer has adopted is theirs, and the
    # generator must be unable to take it back by accident: a new output path
    # that is not machine-owned fails here rather than silently overwriting
    # hand-written work.  See "Who owns which file" in /AGENTS.md.
    trespass = sorted(str(p.relative_to(ROOT)) for p in outputs if not machine_owned(p))
    if trespass:
        fail([f"build.py may not write {p}: it is hand-written. Generate it once, "
              f"then check it instead (tex/ledger.tex is the worked example)."
              for p in trespass])

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in outputs.items()
            if not path.exists() or path.read_text() != content
        ]
        if stale:
            fail([f"stale generated file: {p} (run python tools/build.py)" for p in stale])
        print("generated files up to date")
        return

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content)
        print("wrote", path.relative_to(ROOT))


if __name__ == "__main__":
    main()
