#!/usr/bin/env python3
"""Compile one case on its own: `make preview CASE=logdet-loewner`.

The point of tex/cxcase.sty being a real package is that a case is a real LaTeX
document fragment.  This wraps one counterexamples/<id>/case.tex in a minimal
preamble so it can be typeset while it is being written, without rebuilding the
paper.

What a preview cannot show is metadata, which lives in case.json and reaches
LaTeX through tex/generated/cases.tex: heading level, and whether a quoted
statement is verbatim or a paraphrase.  A preview therefore labels every quote
as a paraphrase.  Run `make paper` for the real thing.

Stdlib only.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT / "tex"

WRAPPER = r"""%% GENERATED by tools/preview_case.py -- a scratch file; delete freely.
\documentclass[11pt]{amsart}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[margin=1in]{geometry}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}
\usepackage{cxcase}
\usepackage{cleveref}
\AtBeginDocument{\let\cite\citep}
\begin{document}
\cxstandalone{%(case)s}
\input{../counterexamples/%(case)s/case.tex}
\bibliographystyle{abbrvnat}
\bibliography{references}
\end{document}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("case", help="case id (the directory under counterexamples/)")
    args = ap.parse_args()

    case_tex = ROOT / "counterexamples" / args.case / "case.tex"
    if not case_tex.exists():
        sys.exit(f"error: {case_tex.relative_to(ROOT)} does not exist")

    wrapper = TEX / f"preview-{args.case}.tex"
    wrapper.write_text(WRAPPER % {"case": args.case})
    proc = subprocess.run(
        ["latexmk", "-pdf", "-interaction=nonstopmode", wrapper.stem], cwd=TEX
    )
    if proc.returncode == 0:
        print(f"\nwrote tex/{wrapper.stem}.pdf")
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
