#!/usr/bin/env python3
"""Compile one case on its own: `make preview CASE=quantum-coupon-collector`.

The point of tex/cxcase.sty being a real package is that a case is a real LaTeX
document fragment.  This wraps one counterexamples/<id>/case.tex in a minimal
preamble so it can be typeset while it is being written, without rebuilding the
paper.

What a preview cannot show is metadata: whether a quoted statement is verbatim
or a paraphrase (from case.json, via tex/generated/metadata.tex) and the heading
level (set by hand in tex/cases.tex).  A preview therefore labels every quote as
a paraphrase.  Run `make paper` for the real thing.

Stdlib only.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT / "tex"
# Previews are scratch, and a scratch file next to the paper's sources is one a
# shell glob keeps catching.  They get their own directory, gitignored whole,
# so `tex/*.tex` stays exactly the files a person writes.
PREVIEW_DIR = TEX / "preview"

WRAPPER = r"""%% GENERATED by tools/preview_case.py -- a scratch file; delete freely.
\documentclass[11pt]{amsart}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[margin=1in]{geometry}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}
\usepackage{cxcase}
\AtBeginDocument{\let\cite\citep}
\begin{document}
\cxstandalone{%(case)s}
\input{../../counterexamples/%(case)s/case.tex}
\bibliographystyle{abbrvnat}
\bibliography{references}
\end{document}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("case", help="case id (the directory under counterexamples/)")
    args = ap.parse_args()

    case_tex = ROOT / "counterexamples" / args.case / "case.tex"
    if not case_tex.exists():
        sys.exit(f"error: {case_tex.relative_to(ROOT)} does not exist")

    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    wrapper = PREVIEW_DIR / f"preview-{args.case}.tex"
    wrapper.write_text(WRAPPER % {"case": args.case})
    # Compiled from tex/preview/, so cxcase.sty and references.bib are one level
    # up: TEXINPUTS and BIBINPUTS say so.  The trailing empty entry keeps the
    # default search path, which is what the leading ':' would otherwise drop.
    env = {
        **os.environ,
        "TEXINPUTS": f"..{os.pathsep}{os.environ.get('TEXINPUTS', '')}",
        "BIBINPUTS": f"..{os.pathsep}{os.environ.get('BIBINPUTS', '')}",
    }
    proc = subprocess.run(
        ["latexmk", "-pdf", "-interaction=nonstopmode", wrapper.stem],
        cwd=PREVIEW_DIR,
        env=env,
    )
    if proc.returncode == 0:
        print(f"\nwrote {wrapper.with_suffix('.pdf').relative_to(ROOT)}")
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
